# Recommended is 256, but it requires JCE to be installed.
symmetricKeySize: 192

# Cache used to relieve the pressure on the database.
publicKeysCache: maximumSize=100, expireAfterAccess=10m

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: sa

  # the password
  password: ""

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/hibernatedb

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.show_sql: false
    hibernate.hbm2ddl.auto: create

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: select 1

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 5

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true

  checkConnectionOnBorrow: true

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

circuitBreaker:
  threshold: 0.5 # failures per second
  rateType: ONE_MINUTE # Last minute rate

swagger:
  resourcePackage: com.github.mtakaki.credentialstorage.resources

logging:
  appenders:
    - type: console
      threshold: INFO
      target: stdout
    - type: logentries
      threshold: WARN
      token: ${env.LOGENTRIES_TOKEN}

metrics:
  frequency: 1 minute                       # Default is 1 second.
  reporters:
    - type: datadog
      transport:
        type: http
        apiKey: ${env.DATADOG_KEY}
        connectTimeout: 1m
        socketTimeout: 1m