# Recommended is 256, but it requires JCE to be installed.
symmetricKeySize: 256

# Cache used to relieve the pressure on the database.
publicKeysCache: maximumSize=100, expireAfterAccess=10m

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders: []

circuitBreaker:
  threshold: 0.5 # failures per second
  rateType: ONE_MINUTE # Last minute rate

swagger:
  resourcePackage: com.github.mtakaki.credentialstorage.resources
  schemes:
    - https

logging:
  level: ${LOG_LEVEL:-'INFO'}
  appenders:
    - type: console
      threshold: ${LOG_LEVEL:-'INFO'}
      target: stdout
      timeZone: ${TIME_ZONE:-'UTC'}

# Jodd Petite dependency injection settings.
petite:
  useFullTypeNames: true
  automagicConfigurator: true
  useMetrics: true

redis:
  url: ${REDIS_URL:-'redis://localhost:6379'}
  poolConfig:
    maxTotal: 10